const linhagem = [
"Argan","Aslan","Anserin","Anubyr","Auroke","Avarin",
"Dhampiro","Drakar","Elfen","Fada","Gajarin","Hellrog",
"Humano","Ikan","Leafen","Leporídeo","Licarin","NanDhur",
"NanZhur","Mamba","Mirath","Retornado","Sylvano","Tarog","Thar",
"Troll","Tuanak","Uriel","Urvolg","Vaporúrgico_Grande", "Vaporúrgico_Pequeno", "Vok","Yullen"
];

const classe = [

"Limpo",    
"Física/Gladiador",
"Física/Soldado",
"Física/Vanguardista",
"Física/Espadachim",
"Física/Explorador",
"Física/Corsário",
"Física/Ladino",
"Física/Acólito",
"Híbrida/Menestrel",
"Híbrida/Engenheiro",
"Híbrida/Lutador",
"Híbrida/Alquimista",
"Híbrida/Sentinela",
"Híbrida/Primalista",
"Híbrida/Haxarim",
"Híbrida/Tecnomante",
"Mística/Arcanista",
"Mística/Xamã",
"Mística/Mago de Sangue",
"Mística/Doutor da Praga",
"Mística/Sacerdote",
"Mística/Bruxo",
"Mística/Rúnico",
"Mística/Telepata"

];

const paradigma = [

"Herói Relutante",
"Sábio Ancião",
"Forasteiro Misterioso",
"Errante Solitário",
"Sábio dos Livros",
"Curioso Incansável",
"Renegado",
"Caçador de Tesouros",
"Senhor das Feras",
"Mentalista",
"Fanático Religioso",
"Mártir",
"Inventor",
"Comediante",
"Ranzinza",
"Visionário",
"Filantropo",
"Boêmio",
"Espertalhão",
"Aristocrata Falido",
"Filósofo de Taberna",
"Fanfarrão"

];

const familia = [

"Silfer",
"Perênia",
"Silfery",
"Kostan",
"Bragano",
"Magallen",
"Roldane",
"Fherrur",
"Rokhar",
"Priotyr",
"Borden",
"Owlzen",
"Morale",
"Dunrram",
"Graystaff"

];

const cidade = [

"AdGlacia/Daglar",
"AdGlacia/Base Laureana",
"AdGlacia/Base Loreana",
"AdGlacia/Base Valondeana",
"AdGlacia/Base Stoneana",
"Aequória/Nactal",
"Aequória/Jirav",
"Aequória/Tenoc Titlan",
"Aetherhaven",
"Laurel/Soundo",
"Laurel/Telúria",
"Laurel/Tolaria",
"Laurel/Ghol",
"Laurel/Raford",
"Laurel/Nylsena",
"Laurel/Falonseri",
"Laurel/Matheas",
"Laurel/Nelhein",
"Laurel/Porto Mainê",
"Laurel/Drucel",
"Laurel/Déllis",
"Laurel/Weadris",
"Laurel/Asterof",
"Laurel/Veissen",
"Laurel/Klumandur",
"Laurel/Dirrokk",
"Laurel/Long Tom Falls",
"Laurel/Ceats",
"Laurel/Forte Bahall",
"Laurel/Criostenes",
"Laurel/Farabelum",
"Laurel/Tallon",
"Laurel/Faeris",
"Lorânia/Melárian",
"Lorânia/Zênia",
"Lorânia/Gaélia",
"Lorânia/Queenlow",
"Lorânia/Kinjab",
"Lorânia/Tomb Mainê",
"Nashima/Fukoma",
"Nashima/Khabai",
"Nashima/Tianjin",
"Nashima/Zancari",
"Nashima/Jamba",
"Nashima/Bahula",
"Nashima/Rachi Lear",
"Stoneholdt/Dann Cale",
"Stoneholdt/Averrin",
"Stoneholdt/Elvenfog",
"Stoneholdt/Wafeld",
"Stoneholdt/Shanto",
"Stoneholdt/Visina",
"Stoneholdt/Stonan",
"Stoneholdt/Dontton Brich",
"Stoneholdt/Mckelor",
"Stoneholdt/Riffolk",
"Stoneholdt/Kal Hari",
"Stoneholdt/Norter",
"Valonde/Alar Sidu",
"Valonde/Frigga",
"Valonde/Haribo",
"Valonde/Oanan",
"Valonde/Enissa",
"Valonde/Árbaro",
"Valonde/Ephatea",
"Valonde/Tiron",
"Valonde/Craven Tir",
"Valonde/Seriba",
"Valonde/Sória",
"Valonde/Naphal",
"Valonde/Besar",
"Valonde/Trisca",
"Valonde/Núvia",
"Valonde/Dãnea",
"Valonde/Tiri Marqash"

];
